import type { Tool, Category } from "@/types/tool";

export const CATEGORIES: Category[] = [
  {
    id: "pdf",
    slug: "pdf-tools",
    name: "PDF Tools",
    description:
      "Convert, merge, split, and edit PDF files online for free. No installation required.",
    icon: "pdfv2",
    color: "text-red-600",
    bgColor: "from-red-50/25 to-red-100",
    borderColor: "border-red-200",
  },
  {
    id: "image",
    slug: "image-tools",
    name: "Image Tools",
    description:
      "Compress, resize, convert, and edit images online. Supports JPG, PNG, WebP and more.",
    icon: "image",
    color: "text-blue-600",
    bgColor: "from-blue-50/25 to-blue-100",
    borderColor: "border-blue-200",
  },
  {
    id: "file",
    slug: "file-converter",
    name: "File Converter",
    description:
      "Convert files between formats instantly. Supports documents, spreadsheets, and more.",
    icon: "file",
    color: "text-green-600",
    bgColor: "from-green-50/25 to-green-100",
    borderColor: "border-green-200",
  },
  {
    id: "ocr",
    slug: "ocr-tools",
    name: "OCR Tools",
    description:
      "Extract text from images and PDFs using AI-powered optical character recognition.",
    icon: "qcr",
    color: "text-orange-600",
    bgColor: "from-orange-50/25 to-orange-100",
    borderColor: "border-orange-200",
  },
  {
    id: "web",
    slug: "web-tools",
    name: "Web Tools",
    description:
      "Free online utilities for developers and designers — QR codes, color palettes, Base64, JSON/CSV editor, HTML tools, and more.",
    icon: "web",
    color: "text-indigo-600",
    bgColor: "from-indigo-50/25 to-indigo-100",
    borderColor: "border-indigo-200",
  },
  {
    id: "social",
    slug: "social-media-tools",
    name: "Social Media Tools",
    description:
      "Free tools for YouTube, Instagram, and social media creators — generate tags, captions, hashtags, fancy text, and format posts for every platform.",
    icon: "love",
    color: "text-rose-600",
    bgColor: "from-rose-50/25 to-rose-100",
    borderColor: "border-rose-200",
  },
  {
    id: "seo",
    slug: "seo-tools",
    name: "SEO Tools",
    description:
      "Free SEO and content tools — keyword generator, meta tag builder, LSI keyword explorer, content idea generator. No signup, 100% browser-based.",
    icon: "rocket",
    color: "text-teal-600",
    bgColor: "from-teal-50/25 to-teal-100",
    borderColor: "border-teal-200",
  },
  {
    id: "dev",
    slug: "developer-tools",
    name: "Developer Tools",
    description:
      "Essential developer utilities — code formatter, regex tester, URL encoder/decoder, JWT decoder. Fast, client-side, no installs needed.",
    icon: "code",
    color: "text-violet-600",
    bgColor: "from-violet-50/25 to-violet-100",
    borderColor: "border-violet-200",
  },
];

export const TOOLS: Tool[] = [
  // PDF Tools
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description:
      "Convert PDF pages to high-quality JPG images online for free. Fast, secure, and easy to use.",
    shortDescription: "Convert PDF pages to JPG images",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📄",
    keywords: [
      "pdf to jpg converter",
      "convert pdf to image online free",
      "pdf to jpg high quality",
      "extract images from pdf",
      "pdf page to jpeg",
      "pdf to image converter",
      "convert pdf to jpg without adobe",
      "pdf to jpg bulk download",
      "export pdf pages as images",
      "pdf to jpeg free online",
    ],
    popular: true,
    acceptedFormats: [".pdf"],
    outputFormat: "JPG",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into one document online. Free PDF merger with no file size limits.",
    shortDescription: "Combine multiple PDFs into one",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📑",
    keywords: [
      "merge pdf online free",
      "combine pdf files",
      "join pdf documents",
      "pdf merger no upload",
      "merge multiple pdfs into one",
      "combine pdf pages online",
      "pdf combiner free",
      "merge pdf without adobe",
      "free pdf merge tool",
      "combine two pdf files online",
    ],
    popular: true,
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description:
      "Split a PDF into multiple separate files. Extract pages from PDF online for free.",
    shortDescription: "Split PDF into separate pages",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "✂️",
    keywords: [
      "split pdf online free",
      "extract pages from pdf",
      "pdf page extractor",
      "split pdf by page range",
      "separate pdf pages online",
      "cut pdf pages online",
      "pdf splitter no upload",
      "divide pdf into parts",
      "extract specific pages from pdf",
      "split pdf without adobe",
    ],
    popular: true,
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description:
      "Convert plain text or .txt files to a downloadable PDF. Choose page size, font, font size, margins, line spacing, and light or dark theme. Add optional header, footer, and page numbers. 100% browser-based — no upload, no signup.",
    shortDescription: "Convert text or .txt files to a formatted PDF",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📝",
    keywords: [
      "text to pdf converter free",
      "convert txt to pdf online",
      "plain text to pdf generator",
      "free text to pdf no signup",
      "online txt to pdf converter",
      "convert notepad text to pdf",
      "text file to pdf download",
      "browser based pdf generator",
      "free pdf creator from text",
      "text to pdf a4 letter size",
    ],
    acceptedFormats: [".txt"],
    outputFormat: "PDF",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    description:
      "Remove specific pages from a PDF file online. Select pages to delete and download the result instantly.",
    shortDescription: "Remove pages from a PDF",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "🗑️",
    keywords: [
      "delete pages from pdf online free",
      "remove pdf pages",
      "pdf page remover",
      "delete specific pages from pdf",
      "remove pages from pdf without acrobat",
      "pdf page deleter online",
      "how to delete a page from pdf online",
      "online pdf editor remove pages",
      "cut pages from pdf free",
      "pdf page removal tool",
    ],
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description:
      "Reduce PDF file size without losing quality. Free online PDF compressor.",
    shortDescription: "Reduce PDF file size online",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "🗜️",
    keywords: [
      "compress pdf online free",
      "reduce pdf file size",
      "pdf compressor no upload",
      "shrink pdf to 100kb",
      "compress pdf without losing quality",
      "make pdf smaller online",
      "pdf file size reducer",
      "compress pdf for email",
      "pdf compressor free tool",
      "reduce pdf size online without quality loss",
    ],
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description:
      "Convert JPG or PNG images to PDF online. Combine multiple images into one PDF file instantly.",
    shortDescription: "Convert images to a PDF file",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "🖼️",
    keywords: [
      "jpg to pdf converter",
      "convert images to pdf online free",
      "multiple photos to pdf",
      "jpeg to pdf free",
      "png to pdf converter",
      "combine images into pdf",
      "image to pdf converter online",
      "photos to pdf no watermark",
      "jpg to pdf without software",
      "convert picture to pdf free",
    ],
    acceptedFormats: [".jpg", ".jpeg", ".png"],
    outputFormat: "PDF",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description:
      "Convert PDF files to editable Word documents online for free. Extract text and download as RTF.",
    shortDescription: "Convert PDF to Word document",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📝",
    keywords: [
      "pdf to word converter free",
      "convert pdf to docx online",
      "extract text from pdf to word",
      "pdf to editable document",
      "pdf to word no software",
      "pdf text to rtf free",
      "convert pdf to word online no email",
      "pdf to word without adobe",
      "pdf to word free online tool",
      "scanned pdf to word text",
    ],
    acceptedFormats: [".pdf"],
    outputFormat: "RTF",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description:
      "Convert Word documents to PDF online for free. Supports .doc and .docx — no account needed.",
    shortDescription: "Convert Word documents to PDF",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📄",
    keywords: [
      "word to pdf converter free",
      "convert docx to pdf online",
      "doc to pdf converter",
      "microsoft word to pdf free",
      "word to pdf no software",
      "save word as pdf online",
      "convert word document to pdf free",
      "docx to pdf without word",
      "word file to pdf converter online",
      "word to pdf best quality",
    ],
    acceptedFormats: [".doc", ".docx"],
    outputFormat: "PDF",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description:
      "Add password protection to PDF files online. Encrypt and lock your PDF with a secure password.",
    shortDescription: "Add password to your PDF",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "🔒",
    keywords: [
      "password protect pdf online free",
      "encrypt pdf with password",
      "add password to pdf online",
      "pdf password protection free",
      "secure pdf online",
      "lock pdf with password free",
      "pdf encryption tool online",
      "protect pdf without adobe",
      "pdf password encryption free tool",
      "how to password protect a pdf online",
    ],
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  // Image Tools

  {
    slug: "image-format-converter",
    name: "Image Format Converter",
    description:
      "Convert images between any format online for free. Supports HEIC, JPG, PNG, WebP, BMP, TIFF. Batch conversion with drag & drop — all client-side.",
    shortDescription: "Convert HEIC, JPG, PNG, WebP, BMP, TIFF",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "🔄",
    keywords: [
      "image format converter online free",
      "heic to jpg converter",
      "webp to jpg converter",
      "png to webp converter",
      "bmp to jpg online",
      "tiff to jpg free",
      "convert heic to png online",
      "batch image converter free",
      "image type converter browser",
      "heic to webp online free",
    ],
    popular: true,
    acceptedFormats: [
      ".heic",
      ".heif",
      ".jpg",
      ".jpeg",
      ".png",
      ".webp",
      ".bmp",
      ".tiff",
      ".tif",
    ],
    outputFormat: "JPG/PNG/WebP",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description:
      "Compress images online without losing quality. Reduce JPG, PNG, WebP file size instantly.",
    shortDescription: "Compress images without quality loss",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "🗜️",
    keywords: [
      "image compressor online free",
      "compress jpg online",
      "compress png file size",
      "reduce image file size without quality loss",
      "image size reducer free",
      "compress webp online",
      "compress images for website free",
      "image file compressor no upload",
      "reduce photo size online free",
      "compress image to 100kb free",
    ],
    popular: true,
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormat: "JPG/PNG/WebP",
  },
  {
    slug: "image-resize",
    name: "Image Resize",
    description:
      "Resize images online to any dimension. Free image resizer that maintains aspect ratio.",
    shortDescription: "Resize images to custom dimensions",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "↔️",
    keywords: [
      "resize image online free",
      "image resizer custom dimensions",
      "resize photo online",
      "change image size online free",
      "resize jpg online free",
      "resize png online",
      "image resize pixels free",
      "resize image without losing quality",
      "resize image for social media",
      "online image resizer no signup",
    ],
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
    outputFormat: "JPG/PNG",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    description:
      "Convert JPG images to PNG format online for free. Lossless conversion with transparency support.",
    shortDescription: "Convert JPG images to PNG format",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "🔁",
    keywords: [
      "jpg to png converter free",
      "convert jpeg to png online",
      "jpg to png lossless",
      "jpeg to png with transparency",
      "change jpg format to png free",
      "convert photo to png online",
      "jpg to png no quality loss",
      "jpg to png converter without software",
      "batch jpg to png online",
      "convert jpg to transparent png",
    ],
    acceptedFormats: [".jpg", ".jpeg"],
    outputFormat: "PNG",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    description:
      "Convert PNG images to JPG format online. Reduce file size while preserving quality.",
    shortDescription: "Convert PNG images to JPG format",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "🔁",
    keywords: [
      "png to jpg converter free",
      "convert png to jpeg online",
      "png to jpg no quality loss",
      "transparent png to jpg converter",
      "change png to jpg format",
      "reduce png file size as jpg",
      "png to jpeg converter online free",
      "convert png to jpg without software",
      "batch png to jpg converter",
      "png to jpg background color",
    ],
    acceptedFormats: [".png"],
    outputFormat: "JPG",
  },
  {
    slug: "gif-maker",
    name: "GIF Maker & Converter",
    description:
      "Create GIFs from images or video online. Convert video to GIF or GIF to MP4. Set frame rate, quality, and resolution. Preview before download.",
    shortDescription: "Create GIF from images or video, convert GIF to MP4",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "🎞️",
    keywords: [
      "gif maker online free",
      "video to gif converter",
      "gif to mp4 converter",
      "create gif from images online",
      "make gif from video free",
      "gif creator browser",
      "video to gif no upload",
      "gif to video converter free",
      "animated gif maker online",
      "gif maker with custom fps",
    ],
    acceptedFormats: [
      ".jpg",
      ".jpeg",
      ".png",
      ".webp",
      ".mp4",
      ".mov",
      ".webm",
      ".gif",
    ],
    outputFormat: "GIF/MP4",
  },
  {
    slug: "image-editor",
    name: "Image Editor",
    description:
      "Free online image editor with resize, crop, rotate, and flip tools. Supports JPG, PNG, WebP. No software needed — works in your browser.",
    shortDescription: "Resize, crop, rotate & flip images online",
    category: "image",
    categorySlug: "image-tools",
    categoryName: "Image Tools",
    icon: "✏️",
    keywords: [
      "image editor online free",
      "crop image online",
      "rotate image online",
      "flip image online",
      "resize image online free",
      "online photo editor no signup",
      "image crop resize rotate free",
      "edit image browser",
      "photo editor online free no download",
      "image flipper online",
    ],
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
    outputFormat: "JPG/PNG/WebP",
  },
  // File Converter
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description:
      "Convert Word documents (DOCX) to PDF online for free. Preserves formatting perfectly.",
    shortDescription: "Convert Word documents to PDF",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "📝",
    keywords: [
      "word to pdf converter free",
      "convert docx to pdf online",
      "doc to pdf converter",
      "microsoft word to pdf free",
      "word to pdf no software",
      "save word as pdf online",
      "convert word document to pdf free",
      "docx to pdf without word",
      "word file to pdf converter online",
      "word to pdf best quality",
    ],
    popular: true,
    acceptedFormats: [".doc", ".docx"],
    outputFormat: "PDF",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description:
      "Convert Excel spreadsheets to PDF format online. Free XLSX to PDF converter.",
    shortDescription: "Convert Excel files to PDF",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "📊",
    keywords: [
      "excel to pdf converter free",
      "convert xlsx to pdf online",
      "xls to pdf free",
      "excel spreadsheet to pdf",
      "convert excel to pdf no office",
      "xlsx to pdf online no software",
      "excel table to pdf converter",
      "batch excel to pdf free",
      "excel to pdf best quality",
      "convert xls to pdf online free",
    ],
    acceptedFormats: [".xls", ".xlsx"],
    outputFormat: "PDF",
  },
  // File Converter – Data Format & Text Tools
  {
    slug: "csv-json-converter",
    name: "CSV ↔ JSON Converter",
    description:
      "Convert CSV files to JSON and JSON arrays to CSV online for free. Bidirectional, instant, 100% in-browser.",
    shortDescription: "Convert CSV to JSON and back",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "🔄",
    keywords: [
      "csv to json converter",
      "json to csv converter",
      "csv to json online free",
      "json to csv online",
      "convert csv to json browser",
      "parse csv to json",
      "json to csv download",
      "csv json converter free",
      "convert json array to csv",
      "csv to json no upload",
    ],
    acceptedFormats: [".csv", ".json"],
    outputFormat: "JSON/CSV",
  },
  {
    slug: "json-xml-converter",
    name: "JSON ↔ XML Converter",
    description:
      "Convert JSON to XML and XML to JSON online for free. Bidirectional converter with live preview.",
    shortDescription: "Convert JSON to XML and back",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "🔁",
    keywords: [
      "json to xml converter",
      "xml to json converter",
      "json to xml online free",
      "xml to json online",
      "convert json to xml browser",
      "json xml converter free",
      "xml to json download",
      "convert xml to json no upload",
      "json to xml formatter",
      "xml json converter tool",
    ],
    acceptedFormats: [".json", ".xml"],
    outputFormat: "JSON/XML",
  },
  {
    slug: "excel-csv-converter",
    name: "Excel ↔ CSV Converter",
    description:
      "Convert Excel spreadsheets to CSV and CSV files to Excel online. Supports .xlsx and .xls — no software needed.",
    shortDescription: "Convert Excel to CSV and back",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "📊",
    keywords: [
      "excel to csv converter",
      "csv to excel converter",
      "xlsx to csv online free",
      "csv to xlsx online",
      "convert excel to csv no software",
      "excel csv converter free",
      "xls to csv converter",
      "csv to excel download",
      "batch excel to csv free",
      "excel csv online tool",
    ],
    acceptedFormats: [".xlsx", ".xls", ".csv"],
    outputFormat: "CSV/XLSX",
  },
  {
    slug: "txt-docx-converter",
    name: "TXT ↔ DOCX Converter",
    description:
      "Convert plain text files to Word DOCX documents and extract text from DOCX files online for free.",
    shortDescription: "Convert TXT to DOCX and back",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "📝",
    keywords: [
      "txt to docx converter",
      "docx to txt converter",
      "convert text to word online free",
      "txt to word converter",
      "word to text extractor free",
      "txt to docx no software",
      "plain text to word document",
      "docx to plain text online",
      "convert txt to word free",
      "text file to word document",
    ],
    acceptedFormats: [".txt", ".docx"],
    outputFormat: "DOCX/TXT",
  },
  {
    slug: "markdown-html-converter",
    name: "Markdown ↔ HTML Converter",
    description:
      "Convert Markdown to HTML and HTML to Markdown online with a live split-pane preview. Fast, free, no signup.",
    shortDescription: "Convert Markdown to HTML with live preview",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "✍️",
    keywords: [
      "markdown to html converter",
      "html to markdown converter",
      "markdown to html online free",
      "md to html live preview",
      "html to markdown online",
      "convert markdown to html",
      "markdown html editor free",
      "md to html converter no signup",
      "html to md converter",
      "markdown preview online",
    ],
    outputFormat: "HTML/MD",
  },
  {
    slug: "zip-tools",
    name: "ZIP Tools",
    description:
      "Create ZIP archives from multiple files and extract ZIP files online for free. 100% client-side, no uploads.",
    shortDescription: "Create and extract ZIP archives online",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "🗜️",
    keywords: [
      "zip creator online free",
      "extract zip file online",
      "create zip archive browser",
      "zip extractor online no software",
      "online zip creator free",
      "zip file creator tool",
      "extract zip no upload",
      "make zip file online",
      "zip files together free",
      "online zip extractor free",
    ],
    acceptedFormats: [".zip", "*"],
    outputFormat: "ZIP",
  },
  {
    slug: "json-viewer",
    name: "JSON Viewer",
    description:
      "View, format, and validate JSON online. Interactive collapsible tree view with syntax highlighting, search, and live structure stats. 100% client-side, no signup.",
    shortDescription: "Format, validate & explore JSON with tree view",
    category: "file",
    categorySlug: "file-converter",
    categoryName: "File Converter",
    icon: "🔍",
    keywords: [
      "json viewer online free",
      "json formatter online",
      "json beautifier free",
      "json validator online",
      "format json online",
      "json tree viewer",
      "json prettifier free",
      "json syntax highlighter",
      "view json file online",
      "json explorer browser",
    ],
    acceptedFormats: [".json"],
    outputFormat: "JSON",
  },
  // Web Tools
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Generate QR codes for URLs, WiFi networks, and vCards online for free. Customize size and color.",
    shortDescription: "Generate QR codes for links, WiFi, and contacts",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "⬛",
    keywords: [
      "qr code generator free online",
      "create qr code for url",
      "wifi qr code generator",
      "vcard qr code creator",
      "custom qr code free",
      "qr code maker no signup",
      "qr code for business card free",
      "qr code generator download png",
      "free qr code with custom color",
      "qr code generator for link sharing",
    ],
    popular: true,
    outputFormat: "PNG",
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description:
      "Generate complementary and analogous color palettes from any hex color. Convert hex to RGB and HSB instantly.",
    shortDescription: "Generate color palettes from any hex color",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "🎨",
    keywords: [
      "color palette generator free",
      "complementary color finder online",
      "hex color palette",
      "analogous color scheme generator",
      "triadic color palette tool",
      "color scheme generator from hex",
      "brand color palette generator",
      "rgb color palette maker",
      "color combination generator online",
      "color harmony tool free",
    ],
    outputFormat: "HEX/RGB",
  },
  {
    slug: "url-shortener",
    name: "URL Shortener",
    description:
      "Shorten long URLs online for free. Generate compact, shareable short links instantly.",
    shortDescription: "Shorten long URLs into compact links",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "🔗",
    keywords: [
      "url shortener free online",
      "shorten link free",
      "free short url generator",
      "url shortener no signup",
      "link shortener for social media",
      "tinyurl alternative free",
      "short url creator online",
      "compact url generator",
      "url shortener no expiry",
      "best free url shortener 2025",
    ],
    popular: true,
    outputFormat: "Short URL",
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description:
      "Encode and decode Base64 strings online. Supports text and file input with instant results.",
    shortDescription: "Encode or decode Base64 text and files",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "🔢",
    keywords: [
      "base64 encoder online free",
      "base64 decoder online",
      "encode text to base64",
      "decode base64 string online",
      "base64 file encoder free",
      "base64 image encoder",
      "convert base64 to text",
      "base64 encode decode tool",
      "online base64 converter",
      "base64 encode file browser",
    ],
    acceptedFormats: ["*"],
    outputFormat: "TXT/Base64",
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF Converter",
    description:
      "Convert HTML code to a downloadable PDF file online. Choose page size and preserve styling.",
    shortDescription: "Convert HTML code to a PDF document",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "📄",
    keywords: [
      "html to pdf converter free",
      "convert html to pdf online",
      "webpage to pdf converter",
      "html code to pdf download",
      "html to pdf no software",
      "save html as pdf online",
      "url to pdf converter free",
      "web page to pdf online",
      "html to pdf a4 format",
      "convert html file to pdf free",
    ],
    outputFormat: "PDF",
  },
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    description:
      "Minify HTML code online by removing comments, whitespace, and redundant characters. Instantly reduce file size.",
    shortDescription: "Minify and compress HTML code online",
    category: "web",
    categorySlug: "web-tools",
    categoryName: "Web Tools",
    icon: "⚡",
    keywords: [
      "html minifier online free",
      "minify html code online",
      "compress html file free",
      "html code optimizer",
      "remove whitespace from html online",
      "html uglifier free",
      "reduce html file size",
      "minify html javascript free",
      "html compressor tool",
      "online html minifier no signup",
    ],
    outputFormat: "HTML",
  },
  // Social Media & Creator Tools
  {
    slug: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    description:
      "Download YouTube video thumbnails in all available resolutions — 1280×720, 480×360, 320×180. Enter a YouTube URL or video ID and save the thumbnail instantly.",
    shortDescription: "Download public YouTube thumbnails in HD",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "🎬",
    keywords: [
      "youtube thumbnail downloader free",
      "download youtube thumbnail hd",
      "youtube video thumbnail extractor",
      "get youtube thumbnail from url",
      "youtube thumbnail 1280x720 download",
      "save youtube thumbnail online",
      "youtube thumbnail grabber free",
      "extract thumbnail from youtube video",
      "youtube thumbnail url download",
      "download youtube cover image free",
    ],
    popular: false,
    outputFormat: "JPG",
  },
  {
    slug: "youtube-tag-generator",
    name: "YouTube Tag Generator",
    description:
      "Generate relevant SEO-optimized tags for your YouTube videos. Enter your video topic and get 20–30 tags to boost discoverability and ranking.",
    shortDescription: "Generate SEO tags for YouTube videos",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "🏷️",
    keywords: [
      "youtube tag generator free",
      "youtube seo tags generator",
      "best youtube tags for views",
      "youtube video tags ideas",
      "generate tags for youtube video",
      "youtube tags finder free",
      "youtube keyword tag generator",
      "youtube tags for more views 2025",
      "auto youtube tag generator",
      "free youtube tags tool",
    ],
    outputFormat: "Tags",
  },
  {
    slug: "youtube-title-optimizer",
    name: "YouTube Title Optimizer",
    description:
      "Generate 5 click-worthy, SEO-optimized YouTube title variants from your draft title. Uses proven power words, emotional triggers, and curiosity patterns.",
    shortDescription: "Generate click-worthy YouTube title variations",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "✍️",
    keywords: [
      "youtube title generator free",
      "clickbait youtube title generator",
      "seo optimized youtube titles",
      "youtube title ideas generator",
      "best youtube title examples",
      "youtube title optimizer tool",
      "generate youtube titles free",
      "youtube video title creator",
      "viral youtube title generator",
      "youtube title for more clicks",
    ],
    outputFormat: "Titles",
  },
  {
    slug: "youtube-description-formatter",
    name: "YouTube Description Formatter",
    description:
      "Create a professional, SEO-friendly YouTube video description with timestamps, links, hashtags, and a call-to-action — formatted and ready to paste.",
    shortDescription: "Format YouTube descriptions with timestamps & SEO",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "📋",
    keywords: [
      "youtube description generator free",
      "youtube description template",
      "youtube video description formatter",
      "youtube description with timestamps",
      "seo youtube description maker",
      "create youtube description online",
      "youtube description formatter free",
      "youtube channel description generator",
      "youtube description with hashtags",
      "youtube description copy paste template",
    ],
    outputFormat: "Text",
  },
  {
    slug: "instagram-bio-font-generator",
    name: "Instagram Bio Font Generator",
    description:
      "Generate stylish Unicode fonts for your Instagram bio. Choose from bold, italic, cursive, bubble, gothic, and more — copy and paste directly into Instagram.",
    shortDescription: "Create stylish fonts for Instagram bio",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "✨",
    keywords: [
      "instagram bio font generator",
      "cool fonts for instagram bio",
      "fancy text for instagram",
      "instagram bio font changer",
      "unicode font generator instagram",
      "stylish text for instagram bio",
      "instagram bio cursive font free",
      "instagram font maker online",
      "copy paste fonts for instagram",
      "fancy letters for instagram bio",
    ],
    outputFormat: "Unicode Text",
  },
  {
    slug: "instagram-caption-generator",
    name: "Instagram Caption Generator",
    description:
      "Generate engaging Instagram captions with the right tone, emojis, and hashtags for your post. Choose mood and niche to get 3 ready-to-use caption ideas.",
    shortDescription: "Generate Instagram captions with emojis",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "💬",
    keywords: [
      "instagram caption generator free",
      "generate captions for instagram",
      "instagram post caption ideas",
      "best instagram captions generator",
      "instagram caption maker online",
      "caption generator for instagram photos",
      "funny instagram caption generator",
      "inspirational instagram caption generator",
      "instagram caption with hashtags free",
      "auto caption generator for instagram",
    ],
    outputFormat: "Captions",
  },
  {
    slug: "instagram-hashtag-generator",
    name: "Instagram Hashtag Generator",
    description:
      "Generate 30 targeted Instagram hashtags for any niche. Get a mix of trending, medium, and niche hashtags to maximize reach — copy all at once.",
    shortDescription: "Generate 30 Instagram hashtags for any niche",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "#️⃣",
    keywords: [
      "instagram hashtag generator free",
      "best hashtags for instagram",
      "instagram hashtags 30 copy paste",
      "niche hashtag generator instagram",
      "instagram hashtag finder free",
      "generate hashtags for instagram post",
      "viral instagram hashtags generator",
      "instagram hashtag tool 2025",
      "hashtag generator for more likes",
      "instagram hashtags by category",
    ],
    outputFormat: "Hashtags",
  },
  {
    slug: "instagram-username-generator",
    name: "Instagram Username Generator",
    description:
      "Generate unique, creative Instagram username ideas based on your name or niche. Get 15+ available-style username suggestions instantly.",
    shortDescription: "Generate creative Instagram username ideas",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "👤",
    keywords: [
      "instagram username generator free",
      "unique instagram username ideas",
      "instagram username creator online",
      "cool instagram usernames generator",
      "instagram handle generator",
      "creative username generator for instagram",
      "instagram name generator for girls",
      "aesthetic instagram username generator",
      "instagram username ideas for brands",
      "available instagram username generator",
    ],
    outputFormat: "Usernames",
  },
  {
    slug: "fancy-text-generator",
    name: "Fancy Text Generator",
    description:
      "Transform plain text into 15+ Unicode font styles — bold, italic, cursive, gothic, double-struck, bubble, small caps, and more. Copy with one click.",
    shortDescription: "Convert text to 15+ Unicode font styles",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "🔤",
    keywords: [
      "fancy text generator free",
      "unicode font generator online",
      "cool text generator copy paste",
      "stylish text generator for social media",
      "bold text generator online",
      "cursive text generator",
      "gothic font text generator",
      "fancy letters for facebook",
      "fancy text for twitter bio",
      "unicode text style converter",
    ],
    outputFormat: "Unicode Text",
  },
  {
    slug: "emoji-text-converter",
    name: "Emoji Text Converter",
    description:
      "Convert your text to emoji-decorated messages. Add relevant emojis automatically after keywords, or replace words with matching emoji symbols.",
    shortDescription: "Decorate text with relevant emojis",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "😊",
    keywords: [
      "emoji text converter online free",
      "add emojis to text automatically",
      "text to emoji converter",
      "emoji generator for text",
      "convert words to emojis",
      "emoji text generator copy paste",
      "emoji message generator",
      "text with emojis generator",
      "auto emoji text tool",
      "emoji keyboard for social media",
    ],
    outputFormat: "Text + Emojis",
  },
  {
    slug: "social-media-post-formatter",
    name: "Social Media Post Formatter",
    description:
      "Format your post for Twitter/X, Instagram, LinkedIn, Facebook, or TikTok. See character counts, platform limits, and get a platform-optimized version.",
    shortDescription: "Format posts for any social media platform",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "📱",
    keywords: [
      "social media post formatter",
      "twitter post formatter",
      "linkedin post formatter free",
      "instagram post format tool",
      "social media text formatter",
      "format posts for multiple platforms",
      "twitter character counter",
      "linkedin article formatter",
      "social post optimizer free",
      "multi platform social media formatter",
    ],
    outputFormat: "Formatted Text",
  },
  {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    description:
      "Generate trending hashtags for any topic across Twitter/X, Instagram, TikTok, LinkedIn, and YouTube. Get categorized hashtags by popularity tier.",
    shortDescription: "Generate hashtags for any topic and platform",
    category: "social",
    categorySlug: "social-media-tools",
    categoryName: "Social Media Tools",
    icon: "📈",
    keywords: [
      "hashtag generator free online",
      "trending hashtags generator",
      "hashtag generator for twitter",
      "tiktok hashtag generator free",
      "linkedin hashtag generator",
      "youtube hashtag generator",
      "best hashtags for any topic",
      "hashtag finder tool free",
      "generate hashtags for post",
      "viral hashtag generator 2025",
    ],
    outputFormat: "Hashtags",
  },
  // OCR Tools
  {
    slug: "ocr-image-to-text",
    name: "OCR Image to Text",
    description:
      "Extract text from images using AI-powered multilingual OCR. Supports 14 languages including Turkish, Arabic and Russian. Batch processing, DOCX export, and confidence highlighting.",
    shortDescription: "Multilingual OCR — extract text from images",
    category: "ocr",
    categorySlug: "ocr-tools",
    categoryName: "OCR Tools",
    icon: "🔍",
    keywords: [
      "ocr image to text online free",
      "multilingual ocr",
      "turkish ocr free",
      "extract text from image",
      "image to text converter ocr",
      "batch ocr processing",
      "ocr with confidence score",
      "scan image to text free",
      "photo to text converter",
      "online ocr no signup",
    ],
    popular: false,
    acceptedFormats: [
      ".jpg",
      ".jpeg",
      ".png",
      ".bmp",
      ".tiff",
      ".webp",
      ".heic",
    ],
    outputFormat: "TXT/DOCX",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description:
      "Extract text from digital and scanned PDFs online. Auto-OCR for image-based pages. Export as TXT, DOCX, or JSON. Batch processing — all in your browser.",
    shortDescription: "Extract text from PDF — digital & scanned",
    category: "ocr",
    categorySlug: "ocr-tools",
    categoryName: "OCR Tools",
    icon: "📋",
    keywords: [
      "pdf to text converter free",
      "scanned pdf ocr extractor",
      "extract text from pdf online",
      "pdf to docx converter",
      "pdf text extraction json",
      "batch pdf to text",
      "pdf ocr fallback",
      "pdf to txt online free",
      "copy text from scanned pdf",
      "pdf text extractor free",
    ],
    acceptedFormats: [".pdf"],
    outputFormat: "TXT/DOCX/JSON",
  },
  {
    slug: "barcode-qr-scanner",
    name: "Barcode & QR Scanner",
    description:
      "Scan QR codes and barcodes from images or live webcam. Supports QR, Code128, EAN-13, UPC, DataMatrix, and more. Also generate custom QR codes for URLs, WiFi, vCards, and text.",
    shortDescription: "Scan QR & barcodes · Generate custom QR codes",
    category: "ocr",
    categorySlug: "ocr-tools",
    categoryName: "OCR Tools",
    icon: "⬛",
    keywords: [
      "qr code scanner online free",
      "barcode scanner from image",
      "webcam barcode scanner browser",
      "scan qr code from image upload",
      "ean-13 barcode reader online",
      "code128 scanner free",
      "qr code generator url wifi vcard",
      "custom qr code color size",
      "barcode qr tool free",
      "qr scanner no app",
    ],
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp", ".bmp"],
    outputFormat: "Text/PNG",
  },
  {
    slug: "ocr-text-editor",
    name: "OCR Text Editor",
    description:
      "Upload an image, extract text with OCR, then edit it in a smart text editor. Features spell check, search & replace, word/char counts, and export to TXT or DOCX.",
    shortDescription: "OCR + smart text editor with search & replace",
    category: "ocr",
    categorySlug: "ocr-tools",
    categoryName: "OCR Tools",
    icon: "✏️",
    keywords: [
      "ocr text editor online",
      "extract and edit text from image",
      "ocr spell check online",
      "search replace ocr text",
      "image to editable text free",
      "ocr word editor online",
      "ocr post processing tool",
      "edit extracted text from image",
      "ocr correction tool free",
      "image text extractor editor",
    ],
    acceptedFormats: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"],
    outputFormat: "TXT/DOCX",
  },

  // PDF Tools (continued)
  {
    slug: "rich-text-to-pdf",
    name: "Rich Text to PDF",
    description:
      "Convert rich-formatted text to PDF online — bold, italic, headings, lists, and more. Choose page size, fonts, margins, header/footer. Free and 100% browser-based.",
    shortDescription: "Formatted text editor → PDF with bold, headings & lists",
    category: "pdf",
    categorySlug: "pdf-tools",
    categoryName: "PDF Tools",
    icon: "📝",
    keywords: [
      "rich text to pdf converter online",
      "formatted text to pdf free",
      "word processor to pdf browser",
      "bold italic text to pdf",
      "online text editor pdf export",
      "html to pdf formatted text",
      "create pdf from rich text",
      "text formatting pdf download",
      "wysiwyg pdf creator online",
      "rich text editor pdf free",
    ],
    isNew: true,
    outputFormat: "PDF",
  },

  // SEO Tools
  {
    slug: "keyword-generator",
    name: "Keyword Generator",
    description:
      "Generate long-tail keywords, question keywords, and LSI variations from any seed topic. Free keyword research tool with CSV export — no API key required.",
    shortDescription: "Generate long-tail & question keywords from any topic",
    category: "seo",
    categorySlug: "seo-tools",
    categoryName: "SEO Tools",
    icon: "🔍",
    keywords: [
      "keyword generator free online",
      "long tail keyword generator",
      "seo keyword research tool free",
      "keyword ideas generator",
      "question keyword generator",
      "keyword suggestions tool",
      "free keyword tool no api",
      "generate keywords for blog",
      "lsi keyword generator",
      "seo content keywords",
    ],
    isNew: true,
  },
  {
    slug: "seo-meta-builder",
    name: "SEO Meta Tag Builder",
    description:
      "Build perfect SEO meta tags — title, description, Open Graph, and Twitter Card — with real-time character counters and Google SERP preview. Copy HTML snippet instantly.",
    shortDescription: "Build title, meta description & OG tags with SERP preview",
    category: "seo",
    categorySlug: "seo-tools",
    categoryName: "SEO Tools",
    icon: "🏷️",
    keywords: [
      "seo meta tag generator free",
      "meta description builder online",
      "open graph tag generator",
      "twitter card meta generator",
      "serp snippet preview tool",
      "html meta tags builder",
      "seo title tag optimizer",
      "og tags generator free",
      "meta description character counter",
      "seo metadata snippet tool",
    ],
    isNew: true,
  },
  {
    slug: "content-idea-generator",
    name: "Content Idea Generator",
    description:
      "Generate blog post titles, content ideas, and topic clusters from any keyword or niche. Perfect for bloggers, marketers, and content creators. Free, instant, no signup.",
    shortDescription: "Generate blog ideas, titles & topic clusters from a keyword",
    category: "seo",
    categorySlug: "seo-tools",
    categoryName: "SEO Tools",
    icon: "💡",
    keywords: [
      "content idea generator free",
      "blog post idea generator",
      "content topic generator online",
      "blog title generator seo",
      "content marketing ideas tool",
      "blog idea generator from keyword",
      "content cluster generator",
      "pillar page ideas generator",
      "blog post title ideas free",
      "content strategy tool free",
    ],
    isNew: true,
  },
  {
    slug: "lsi-keyword-explorer",
    name: "LSI Keyword Explorer",
    description:
      "Discover LSI (Latent Semantic Indexing) keywords and semantic variations to boost your content's topical authority. Free related keyword finder with export.",
    shortDescription: "Find LSI & semantic keywords to boost topical authority",
    category: "seo",
    categorySlug: "seo-tools",
    categoryName: "SEO Tools",
    icon: "🌐",
    keywords: [
      "lsi keyword finder free",
      "semantic keyword explorer",
      "related keywords generator",
      "topical authority keywords",
      "lsi keywords for seo",
      "semantic seo keyword tool",
      "co-occurrence keywords tool",
      "entity keyword explorer",
      "related search terms generator",
      "niche keyword variations free",
    ],
    isNew: true,
  },

  // Developer Tools
  {
    slug: "code-formatter",
    name: "Code Formatter & Minifier",
    description:
      "Format and minify JavaScript, CSS, HTML, JSON, and SQL code online. Beautify messy code or minify for production — instant, client-side, no upload required.",
    shortDescription: "Format or minify JS, CSS, HTML, JSON & SQL instantly",
    category: "dev",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    icon: "🧹",
    keywords: [
      "code formatter online free",
      "javascript formatter beautifier",
      "css minifier online",
      "html formatter online free",
      "json beautifier online",
      "sql formatter online",
      "code minifier online",
      "js beautify online",
      "css beautifier free",
      "code beautify minify tool",
    ],
    isNew: true,
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description:
      "Test and debug regular expressions online with real-time match highlighting, group capture display, and flag controls. Supports JavaScript regex syntax.",
    shortDescription: "Test regex patterns with live match highlighting & groups",
    category: "dev",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    icon: "🔬",
    keywords: [
      "regex tester online free",
      "regular expression tester",
      "regex debugger online",
      "javascript regex tester",
      "regex pattern matcher online",
      "regex match highlighter",
      "online regex validator",
      "regex group capture tester",
      "test regular expression online",
      "regex flags tester free",
    ],
    isNew: true,
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder / Decoder",
    description:
      "Encode or decode URLs and query strings online. Supports full URL encode/decode and component-level encoding. Instant, client-side, no data sent to server.",
    shortDescription: "Encode & decode URLs and query strings instantly",
    category: "dev",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    icon: "🔗",
    keywords: [
      "url encoder decoder online",
      "encode url online free",
      "decode url online",
      "url encode special characters",
      "percent encoding decoder",
      "query string encoder online",
      "url component encode decode",
      "uri encoder online",
      "url escape characters tool",
      "encode decode url free",
    ],
    isNew: true,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description:
      "Decode and inspect JSON Web Tokens (JWT) online. View header, payload, and signature parts. Check expiry and claims without sending tokens to any server.",
    shortDescription: "Decode JWT tokens and inspect header, payload & claims",
    category: "dev",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    icon: "🔑",
    keywords: [
      "jwt decoder online free",
      "json web token decoder",
      "jwt inspector online",
      "decode jwt token browser",
      "jwt claims viewer",
      "jwt header payload decoder",
      "jwt expiry checker online",
      "json web token analyzer",
      "jwt debugger free",
      "decode bearer token online",
    ],
    isNew: true,
  },
];

export function getToolsByCategory(categorySlug: string): Tool[] {
  const category = CATEGORIES.find((c) => c.slug === categorySlug);
  if (!category) return [];
  return TOOLS.filter((t) => t.category === category.id);
}

export function getPopularTools(): Tool[] {
  return TOOLS.filter((t) => t.popular);
}

export function getToolBySlug(
  categorySlug: string,
  toolSlug: string,
): Tool | undefined {
  return TOOLS.find(
    (t) => t.categorySlug === categorySlug && t.slug === toolSlug,
  );
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.includes(q)),
  );
}
