import type { Metadata } from "next";
import ToolPageLayout from "@/components/tools/ToolPageLayout";
import JsonLd from "@/components/seo/JsonLd";
import YouTubeThumbnailClient from "./YouTubeThumbnailClient";
import { buildToolMetadata, SITE_URL } from "@/lib/metadata";
import { buildWebAppSchema, buildBreadcrumbSchema, buildFaqSchema } from "@/lib/structured-data";

export const metadata: Metadata = buildToolMetadata({
  toolName: "YouTube Thumbnail Downloader",
  toolDescription:
    "Download YouTube video thumbnails in HD quality for free. Supports 1280×720, 480×360, and smaller sizes. Enter a YouTube URL or video ID and save instantly — no login needed.",
  categorySlug: "social-media-tools",
  toolSlug: "youtube-thumbnail-downloader",
  keywords: [
    "youtube thumbnail downloader free",
    "download youtube thumbnail hd",
    "youtube video thumbnail extractor",
    "get youtube thumbnail from url",
    "youtube thumbnail 1280x720 download",
    "save youtube thumbnail online",
    "youtube thumbnail grabber free",
    "extract thumbnail from youtube video",
    "youtube cover image download",
    "youtube thumbnail url online",
  ],
});

const FAQS = [
  {
    question: "How do I download a YouTube thumbnail?",
    answer:
      "Paste the YouTube video URL or video ID into the input box, click 'Get Thumbnail', choose your preferred resolution, and click the Download button.",
  },
  {
    question: "What thumbnail resolutions are available?",
    answer:
      "We fetch up to four sizes: Max Resolution (1280×720), High Quality (480×360), Medium Quality (320×180), and Standard (120×90). Not all videos have maxresdefault available.",
  },
  {
    question: "Is downloading a YouTube thumbnail legal?",
    answer:
      "Thumbnails are publicly accessible images served by YouTube's own CDN. Downloading them for personal use, reference, or design inspiration is generally acceptable. Do not republish a creator's thumbnail as your own without permission.",
  },
  {
    question: "Why is the Max Resolution thumbnail a grey image?",
    answer:
      "Not all videos have a 1280×720 thumbnail generated by YouTube. In that case, the HQ (480×360) version will be the highest quality available.",
  },
  {
    question: "Does this tool download the actual video?",
    answer:
      "No. This tool only downloads the thumbnail image (a JPEG file). It does not download any video content.",
  },
];

export default function YouTubeThumbnailPage() {
  return (
    <>
      <JsonLd
        data={buildWebAppSchema({
          name: "YouTube Thumbnail Downloader",
          description: "Download YouTube video thumbnails in all available resolutions.",
          slug: "youtube-thumbnail-downloader",
          categorySlug: "social-media-tools",
        })}
      />
      <JsonLd
        data={buildBreadcrumbSchema([
          { name: "Home", url: SITE_URL },
          { name: "Social Media Tools", url: `${SITE_URL}/social-media-tools` },
          { name: "YouTube Thumbnail Downloader", url: `${SITE_URL}/social-media-tools/youtube-thumbnail-downloader` },
        ])}
      />
      <JsonLd data={buildFaqSchema(FAQS)} />
      <ToolPageLayout
        breadcrumbs={[
          { label: "Social Media Tools", href: "/social-media-tools" },
          { label: "YouTube Thumbnail Downloader" },
        ]}
        title="YouTube Thumbnail Downloader – Download HD Thumbnails Free"
        description="Enter any YouTube video URL and download its thumbnail in up to 1280×720 (HD) resolution. Free, instant, no login needed."
        howToSteps={[
          { title: "Paste YouTube URL", description: "Copy any YouTube video URL or video ID and paste it into the input field." },
          { title: "Click Get Thumbnail", description: "Press the button to load all available thumbnail sizes for that video." },
          { title: "Download Your Size", description: "Choose your preferred resolution and click Download to save the JPEG image." },
        ]}
        benefits={[
          { title: "Up to 4 Resolutions", description: "Get Max (1280×720), HQ (480×360), MQ (320×180), and default thumbnails." },
          { title: "Any YouTube URL Format", description: "Supports full URLs, youtu.be short links, Shorts, and plain video IDs." },
          { title: "Instant Preview", description: "See the thumbnail before you download to confirm it's the right video." },
          { title: "No Login Required", description: "Works instantly with no account, no API key, and no limits." },
        ]}
        faqs={FAQS}
      >
        <YouTubeThumbnailClient />
      </ToolPageLayout>
    </>
  );
}
